### PR TITLE
update TODAYS_DATE macro in ossimutilities

### PR DESCRIPTION
**Pull request by rashadkm**
This also fixes one issue in https://github.com/ossimlabs/ossim/issues/6

### CODE REVIEW

**Comment by gpotts** [comment]
Hello Rashad:

Awesome!

Is it possible if you could rebase off the dev branch and do the pull request from that branch?   I’ll then take a look at it and then merge them.


Thank you and take care


Garrett

On Dec 7, 2015, at 2:41 PM, Rashad <notifications@github.com<mailto:notifications@github.com>> wrote:


This also fixes one issue in #6<https://github.com/ossimlabs/ossim/issues/6>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ossimlabs/ossim/pull/7

Commit Summary

  *   ENH: cmake version for 2.8 for all platforms
  *   use cmake string(TIMESTAMP.. to get date

File Changes

  *   M CMakeLists.txt<https://github.com/ossimlabs/ossim/pull/7/files#diff-0> (6)
  *   M cmake/CMakeModules/OssimUtilities.cmake<https://github.com/ossimlabs/ossim/pull/7/files#diff-1> (33)

Patch Links:

  *   https://github.com/ossimlabs/ossim/pull/7.patch
  *   https://github.com/ossimlabs/ossim/pull/7.diff

**Comment by rashadkm** [comment]
here
https://github.com/ossimlabs/ossim/pull/8

**Comment by gpotts** [comment]
Hello Rashad:


On the merge line it is showing:


rashadkm<https://github.com/rashadkm> wants to merge 2 commits into ossimlabs:master from rashadkm:master
+2 −37 
<https://github.com/ossimlabs/ossim/pull/8>


Instead of branch “dev”?  Is there a way for the edits to be applied to dev with a new pull request?



Take care

Garrett


On Dec 7, 2015, at 2:54 PM, Rashad <notifications@github.com<mailto:notifications@github.com>> wrote:


here
#8<https://github.com/ossimlabs/ossim/pull/8>

**Comment by rashadkm** [comment]
what about the other pr?

https://github.com/ossimlabs/ossim/pull/8

**Comment by gpotts** [comment]
Hello Rashad:


Which other pr?  Are you talking about the CmakeList and the cmake utilitities?


Take care

Garrett

On Dec 7, 2015, at 3:05 PM, Rashad <notifications@github.com<mailto:notifications@github.com>> wrote:


what about the other pr?

#8<https://github.com/ossimlabs/ossim/pull/8>

**Comment by rashadkm** [comment]
i will close it and repen against  ossimlabs:dev

**Comment by rashadkm** [comment]
how is this PR 9 - https://github.com/ossimlabs/ossim/pull/9

**Comment by gpotts** [comment]
Hello Rashad:

Thank you for the addition.  That is much simpler than the original way!


All changes merged


Take care

Garrett

On Dec 7, 2015, at 3:19 PM, Rashad <notifications@github.com<mailto:notifications@github.com>> wrote:


how is this PR 9 - #9<https://github.com/ossimlabs/ossim/pull/9>

**Comment by rashadkm** [comment]
Thanks. sorry for previous PR's. I was a bit of hurry today.

**Comment by gpotts** [comment]
Hey Rashad:

No worries.  Thank you for the fix!


Take care


Garrett

On Dec 7, 2015, at 4:03 PM, Rashad <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks. sorry for previous PR's. I was a bit of hurry today.

**Pull request closed without merging**
