### PR TITLE
build fails on windows with msvc

### PR DESCRIPTION
**Pull request by rkanavath**
The two commits are needed to fix ossim compilation on windows

### CODE REVIEW

**Comment by gpotts** [comment]
Working some other items.  Will review the modifications today

**Comment by rkanavath** [comment]
here is the unresolved link error

Linking CXX shared library ..\..\Release\ossim.dll
   CrΘation de la bibliothΦque ..\..\Release\ossim.lib et de l'objet ..\..\Release\ossim.exp
ossimNitfTileSource.cpp.obj : error LNK2019: symbole externe non rΘsolu "public: static bool __cdecl ossimN
itfTileSource_12::uncompressJpeg12Block(unsigned int,unsigned int,class ossimRefPtr<class ossimImageData>,c
lass ossimNitfImageHeader *,class ossimIpt,class std::vector<unsigned char,class std::allocator<unsigned ch
ar> >,unsigned int,unsigned int)" (?uncompressJpeg12Block@ossimNitfTileSource_12@@SA_NIIV?$ossimRefPtr@Voss
imImageData@@@@PAVossimNitfImageHeader@@VossimIpt@@V?$vector@EV?$allocator@E@std@@@std@@II@Z) rΘfΘrencΘ dan
s la fonction "protected: virtual bool __thiscall ossimNitfTileSource::uncompressJpegBlock(unsigned int,uns
igned int)" (?uncompressJpegBlock@ossimNitfTileSource@@MAE_NII@Z)
..\..\Release\ossim.dll : fatal error LNK1120: 1 externes non rΘsolus
LINK failed. with 1120
NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe"' : code retour '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : code
retour '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : code
retour '0x2'
Stop.

C:\OSGeo4W\usr\src\osgeo4w\ossim\ossim-1.8.20-build>nmake

**Comment by rkanavath** [comment]
moving ossimNitfTileSource_12::uncompressJpeg12Block() definition from ossimNitfTileSource_12.cpp to ossimNitfTileSource_12.h fixes this compilation error.

can anyone explain this behavior?

**Comment by rkanavath** [comment]
another one 

ossim-gsoc1.cpp.obj : error LNK2019: symbole externe non rΘsolu "__declspec(dllimport) public: __thiscall o
ssimGenericPointCloudHandler::ossimGenericPointCloudHandler(class std::vector<class ossimEcefPoint,class st
d::allocator<class ossimEcefPoint> > &)" (__imp_??0ossimGenericPointCloudHandler@@QAE@AAV?$vector@VossimEce
fPoint@@V?$allocator@VossimEcefPoint@@@std@@@std@@@Z) rΘfΘrencΘ dans la fonction _main
ossim-gsoc1.cpp.obj : error LNK2001: symbole externe non rΘsolu "public: virtual unsigned int __thiscall os
simGenericPointCloudHandler::getNumPoints(void)const " (?getNumPoints@ossimGenericPointCloudHandler@@UBEIXZ
)
ossim-gsoc1.cpp.obj : error LNK2001: symbole externe non rΘsolu "public: virtual unsigned int __thiscall os
simGenericPointCloudHandler::getFieldCode(void)const " (?getFieldCode@ossimGenericPointCloudHandler@@UBEIXZ
)
ossim-gsoc1.cpp.obj : error LNK2001: symbole externe non rΘsolu "public: virtual bool __thiscall ossimGener
icPointCloudHandler::open(class ossimFilename const &)" (?open@ossimGenericPointCloudHandler@@UAE_NABVossim
Filename@@@Z)
ossim-gsoc1.cpp.obj : error LNK2001: symbole externe non rΘsolu "public: virtual void __thiscall ossimGener
icPointCloudHandler::close(void)" (?close@ossimGenericPointCloudHandler@@UAEXXZ)
ossim-gsoc1.cpp.obj : error LNK2001: symbole externe non rΘsolu "public: virtual void __thiscall ossimGener
icPointCloudHandler::getFileBlock(unsigned int,class ossimPointBlock &,unsigned int)const " (?getFileBlock@
ossimGenericPointCloudHandler@@UBEXIAAVossimPointBlock@@I@Z)
ossim-gsoc1.cpp.obj : error LNK2019: symbole externe non rΘsolu "__declspec(dllimport) public: virtual __th
iscall ossimGenericPointCloudHandler::~ossimGenericPointCloudHandler(void)" (__imp_??1ossimGenericPointClou
dHandler@@UAE@XZ) rΘfΘrencΘ dans la fonction "public: virtual void * __thiscall ossimGenericPointCloudHandl
er::`scalar deleting destructor'(unsigned int)" (??_GossimGenericPointCloudHandler@@UAEPAXI@Z)
..\..\Release\ossim-gsoc1.exe : fatal error LNK1120: 7 externes non rΘsolus
LINK failed. with 1120
NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe"' : code retour '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : code
retour '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"' : code
retour '0x2'
Stop.

**Comment by gpotts** [comment]
Are the merges ready to be applied?

**Comment by rkanavath** [comment]
compilation works on MSVC 2012 32bit.

I am now building ossim for MSVC 2012 64bit. Hoping that it goes well, I would say that merges are ready!
you can review and merge it. I will update to you about the 64bit compilation in an hr or two.

**Comment by gpotts** [comment]
Hello Rashad:

I’ll merge and then lets see about rebasing you to the develope branch.  I’ll merge into the master and then update develop


Take care

Garrett

On Nov 3, 2015, at 9:46 AM, Rashad Kanavath <notifications@github.com<mailto:notifications@github.com>> wrote:


compilation works on MSVC 2012 32bit.

I am now building ossim for MSVC 2012 64bit. Hoping that it goes well, I would say that merges are ready!
you can review and merge it. I will update to you about the 64bit compilation in an hr or two.

**Comment by rkanavath** [comment]
Thanks Garret.  Next time I will make the PR against the develop branch.
Is this the develop branch

https://github.com/ossimlabs/ossim/tree/dev

**Comment by gpotts** [comment]
Hello:

Yes. Thank you for the build fixes!  I am going to merge them in about 5 minutes.


Take care

Garrett

On Nov 3, 2015, at 10:23 AM, Rashad Kanavath <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Garret. Next time I will make the PR against the develop branch.
Is this the develop branch

https://github.com/ossimlabs/ossim/tree/dev

**Comment by rkanavath** [comment]
hi again,

even though i can compile, there is still crash on using ossim executables. Maybe moving the static definition into header was not the right thing.

**Comment by rkanavath** [comment]
I tried excluding ossimNitfTileSource_12 just for msvc compilers and everthing is working
compilation and running ossim executables. I tested ossim-info.exe, ossim-adrg-dump.exe etc..

@gpotts 
exculding ossimNitfTileSource_12 with an ifndef _MSC_VER is acceptable ?.

**Comment by gpotts** [comment]
Hello Rashad:


I am going to rebase the dev branch.  You might need to re-checout the dev branch once completed.  We seem to have a problem with it.  I am working on windows building for the new compiler so it might take a few to get to the point where you are at.   I’ll let you know if I get at least the core building on windows so I can test if I get the same core dump.



Take care

Garrett

On Nov 3, 2015, at 11:16 AM, Rashad Kanavath <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried excluding ossimNitfTileSource_12 just for msvc compilers and everthing is working
compilation and running ossim executables. I tested ossim-info.exe, ossim-adrg-dump.exe etc..

@gpotts<https://github.com/gpotts>
exculding ossimNitfTileSource_12 with an ifndef _MSC_VER is acceptable ?.

**Comment by gpotts** [comment]
Hello Rashad:

Both trees should be in sync now.  You can try the dev branch.  Might want to re-base/re-fork.


Take care
Garrett

On Nov 3, 2015, at 11:16 AM, Rashad Kanavath <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried excluding ossimNitfTileSource_12 just for msvc compilers and everthing is working
compilation and running ossim executables. I tested ossim-info.exe, ossim-adrg-dump.exe etc..

@gpotts<https://github.com/gpotts>
exculding ossimNitfTileSource_12 with an ifndef _MSC_VER is acceptable ?.

**Comment by rkanavath** [comment]
okay. Good that both are in sync now.

Also I think instead of ifndef' ing ossimNitfTileSource_12 class out of source, I can move the only 3 functions in this class to ossimNitfTileSource. Because if the static member functions was giving __stdcall vs __cdecl undefined reference (long story actually) that will solve issues on windows without a miss of any functionality.

I will look it tomorrow at work.  And will create another PR from 'dev' branch.

**Pull request merged**
