### PR TITLE
cmake script fixes

### PR DESCRIPTION
**Pull request by rkanavath**
* add c++11 as required standard
* use OSSIM_LIB_NAME to modify library name ("ossim" is default)
* fixes issue #114

### CODE REVIEW

**Comment by gpotts** [comment]
Looking at the modifications now.  May take a few.  Not sure about all platforms yet for the jpeg12 versus libjpeg12 prefix for headers.  Will see if I can get Burke to look at the jpeg12 modifications

**Comment by rkanavath** [comment]
changes to Nitf source should be reverted. I will replace the file with one from dev.
you can take care of cmake changes.

**Comment by gpotts** [comment]
Hello Rashad.  Thank you for the modifications.   I also see that your dev might be out of sync??  I see a change that says "Merge remote-tracking branch 'upstream/dev' into dev" that seems your local dev is out of sync with the remote? I am checking the CMAKE modifications now.  Testing first on my MAC build then will check it in and then test on the CentOS7 build.  

Will let you know when to do an update and verify.

Thank you again!

**Comment by rkanavath** [comment]
pr updated now

**Comment by gpotts** [comment]
Hello Rashad.  Could you verify.  I manually looked at your changes and pushed them to DEV.  Builds on both MAC and my CentOS box.  I did not execute the merge on the pull request but instead go through the pull request and merge items into my local dev.

Take care

**Comment by rkanavath** [comment]
I will check the current 'dev' from ossimlabs/ossim this evening and let you know
Thanks for your review and merge

**Comment by rkanavath** [comment]
did a quick look in to OssimUtilities.cmake file. one change is missed in your merge.
see: https://github.com/ossimlabs/ossim/pull/119/files#diff-c2cafb9d1964137cd1a44e4752de4d75R183

and ossimlabs/dev
https://github.com/ossimlabs/ossim/blob/dev/cmake/CMakeModules/OssimUtilities.cmake#L180

the line is ADD_DEPENDENCIES(). This make sure all applications depend (or wait) on ossim lib. all apps will be re-built if your libossim changes.
```

+      ENDIF(APPLICATION_COMMAND_LINE)
-
+ 
+    ADD_DEPENDENCIES(${TARGET_TARGETNAME} ${OSSIM_LIB_NAME})
```

**Comment by gpotts** [comment]
Hello Rashad.  Added the missing line

**Comment by omarossim** [comment]
Hello Rashad:

Looking at the builds on CentOS/unix The headers from the sub projects such as ossim-oms, … etc are not being installed now.  Not sure why.


Take care

Garrett

**Comment by rkanavath** [comment]
Can you send me build log. I can have a look and see if this was my changes.

**Comment by rkanavath** [comment]
there is another commit in ossim-oms.

**Comment by gpotts** [comment]
Hello Rashad:

I am going to have to revert the cmake changes for now.  I am getting link errors with ossim-oms and the ossim headers get installed but no other headers are being installed.  Not sure why that is.

**Comment by gpotts** [comment]
Can you verify on a unix system that you can build and install the include headers?  Let's do just a pull request for the cmake files

**Comment by gpotts** [comment]
Added the GEOS QUIET back into dev and also added "CMake: update cmake module path" to dev.

**Comment by rkanavath** [comment]
i confirm that i can install libossim and then build ossim-oms

**Comment by gpotts** [comment]
Hello Rashad:

Just merged both ossim and oms and testing the build on the build server.

**Comment by rkanavath** [comment]
Hope it works now.

**Comment by gpotts** [comment]
Hello Rashad:

I think all tests have passed and the build is good :).  Thank you and take care

**Pull request merged**
