### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by gpotts**

### CODE REVIEW

**Comment by rashadkm** [comment]
Hi garret,

could we use a CMAKE_PREFIX_PATH to detect libs automagically by cmake rather than all those <dependency>_DIR/lib etc.? 
https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html

This make find_library() easier and customizable because anything can come in cmake_prefix_path.

**Comment by gpotts** [comment]
Hello Rashad:


Very cool!  I’ll read up on the use form the link you sent and take a look at it.

Thank you and take care!

Garrett

**Comment by rashadkm** [comment]
If you need, I can give a PR for that ;)

On Sat, Jan 16, 2016 at 2:25 PM, gpotts <notifications@github.com> wrote:

> Hello Rashad:
>
>
> Very cool! I’ll read up on the use form the link you sent and take a look
> at it.
>
> Thank you and take care!
>
> Garrett
>
> > On Jan 15, 2016, at 3:26 PM, Rashad <notifications@github.com> wrote:
> >
> > Hi garret,
> >
> > could we use a CMAKE_PREFIX_PATH to detect libs automagically by cmake
> rather than all those _DIR/lib etc.?
> > https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html <
> https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html>
> > This make find_library() easier and customizable because anything can
> come in cmake_prefix_path.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/ossimlabs/ossim/pull/16#issuecomment-172083099>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ossimlabs/ossim/pull/16#issuecomment-172205490>.
>



-- 
Regards,
   Rashad

**Comment by gpotts** [comment]
Hello Rashad:

Reading about this item I am assuming in our finds that we have we need to add to the search paths the CMAKE_PREFIX_PATH.   Wasn’t sure if it was automatic or not though. 


Take care

Garrett

**Pull request merged**
